In [1]:
#we know how to make mlps now, let's see if we can use the MFCCs of each sample in a 3 second waveform of an 
#instrument to classify them.

import numpy as np
from random import random
from sklearn.model_selection import train_test_split
import tensorflow as tf


#instruments are in folder: IRMAS-TrainingData

In [2]:
#making the data
import os
import librosa
import librosa.display
import IPython.display as ipd
import matplotlib.pyplot as plt
folder_name = 'IRMAS-TrainingData'
sub_folders = [
'cel',
'cla',
'voi',
'gac',
'gel',
'org',
'pia',
'sax',
'tru',
'vio',
'flu']


audio_mfccs = []
targets = []
itera = 0
for sub in sub_folders:
    directory = folder_name + '/' + sub
    for filename in os.listdir(directory):
        print('filename: {}'.format(filename))
        audio_file = directory + '/' + filename
        signal, sr = librosa.load(audio_file)
        mfccs = librosa.feature.mfcc(signal, n_mfcc=20, sr=sr)
        audio_mfccs.append(mfccs)#get those mfccs
        target = np.zeros(11)#length of subfoldiers
        for i,sub in enumerate(sub_folders):
            if sub in filename:
                target[i] = 1
        targets.append(target)
        print(target)
        print(itera/6705)
        itera+=1
audio_mfccs = np.array(audio_mfccs)
targets = np.array(targets)
        
                
                
                
        
        
        
        



filename: 089__[cel][nod][cla]0026__3.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0
filename: [cel][pop_roc]0096__2.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.00014914243102162565
filename: 056__[cel][nod][cla]0038__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0002982848620432513
filename: 013__[cel][nod][cla]0025__3.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.00044742729306487697
filename: [cel][pop_roc]0014__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0005965697240865026
filename: [cel][cla]0113__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0007457121551081282
filename: [cel][cla]0070__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0008948545861297539
filename: [cel][cla]0125__3.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0010439970171513796
filename: [cel][pop_roc]0088__2.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0011931394481730052
filename: 090__[cel][nod][cla]0024__3.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0013422818791946308
filename: [cel][pop_roc]0006__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0

[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.013422818791946308
filename: [cel][cla]0072__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.013571961222967934
filename: [cel][jaz_blu]0009__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.01372110365398956
filename: [cel][pop_roc]0094__2.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.013870246085011185
filename: [cel][pop_roc]0016__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.014019388516032811
filename: [cel][pop_roc]0094__3.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.014168530947054437
filename: [cel][pop_roc]0143__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.014317673378076063
filename: 115__[cel][nod][cla]0055__1.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.014466815809097689
filename: [cel][pop_roc]0120__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.014615958240119313
filename: [cel][cla]0072__3.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.01476510067114094
filename: 106__[cel][nod][cla]0028__3.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.014914243102162566
filename: [cel][cla]00

[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.026845637583892617
filename: 042__[cel][nod][cla]0042__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.026994780014914243
filename: [cel][pop_roc]0092__2.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.02714392244593587
filename: [cel][pop_roc]0010__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.027293064876957495
filename: [cel][cla]0017__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.02744220730797912
filename: [cel][cla]0117__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.027591349739000747
filename: [cel][jaz_blu]0011__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.02774049217002237
filename: [cel][cla]0109__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.027889634601043996
filename: [cel][cla]0074__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.028038777032065622
filename: 057__[cel][nod][cla]0036__3.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.028187919463087248
filename: 117__[cel][nod][cla]0050__1.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.028337061894108874
filename: [cel][cla]0121_

[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0401193139448173
filename: [cel][pop_roc]0133__2.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.040268456375838924
filename: 127__[cel][nod][cla]0047__3.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.04041759880686055
filename: [cel][jaz_blu]0067__3.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.040566741237882176
filename: [cel][cla]0080__3.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0407158836689038
filename: [cel][cla]0080__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.04086502609992543
filename: [cel][cla]0002__1.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.041014168530947054
filename: [cel][jaz_blu]0067__2.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.04116331096196868
filename: [cel][pop_roc]0099__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.041312453392990306
filename: [cel][jaz_blu]0086__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.04146159582401193
filename: 012__[cel][nod][cla]0043__1.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.04161073825503356
filename: [cel][pop_roc]0133__3.w

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.05339299030574198
filename: 032__[cel][nod][cla]0033__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.05354213273676361
filename: 065__[cel][nod][cla]0059__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.053691275167785234
filename: [cel][pop_roc]0060__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.05384041759880686
filename: [cel][cla]0079__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.053989560029828486
filename: [cel][jaz_blu]0061__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.05413870246085011
filename: [cel][pop_roc]0103__1.wav
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.05428784489187174
filename: [cel][cla]0004__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.054436987322893364
filename: [cel][cla]0075__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.05458612975391499
filename: [cel][cla]0108__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.054735272184936616
filename: [cel][cla]0008__2.wav
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.05488441461595824
filename: [cel][pop_roc]0111__1.wav
[1.

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.06696495152870992
filename: [cla][pop_roc]0179__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.06711409395973154
filename: [cla][jaz_blu]0178__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.06726323639075317
filename: [cla][pop_roc]0207__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0674123788217748
filename: [cla][pop_roc]0307__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.06756152125279642
filename: [cla][cla]0189__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.06771066368381805
filename: 144__[cla][nod][cla]0232__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.06785980611483967
filename: [cla][cla]0150__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0680089485458613
filename: [cla][cla]0265__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.06815809097688293
filename: [cla][jaz_blu]0176__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.06830723340790455
filename: 030__[cla][nod][cla]0240__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.06845637583892618
filename: [cla][pop_roc]0169__2.wav
[

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.08038777032065622
filename: [cla][cla]0257__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.08053691275167785
filename: [cla][pop_roc]0291__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.08068605518269947
filename: [cla][cla]0162__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0808351976137211
filename: 101__[cla][nod][cla]0213__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.08098434004474273
filename: 098__[cla][nod][cla]0246__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.08113348247576435
filename: [cla][jaz_blu]0172__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.08128262490678598
filename: [cla][jaz_blu]0156__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0814317673378076
filename: [cla][pop_roc]0301__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.08158090976882923
filename: 180__[cla][nod][cla]0227__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.08173005219985086
filename: [cla][cla]0326__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.08187919463087248
filename: [cla][jaz_blu]0282__2

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.09381058911260254
filename: [cla][cla]0259__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.09395973154362416
filename: [cla][jaz_blu]0280__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.09410887397464579
filename: 083__[cla][nod][cla]0238__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.09425801640566742
filename: 135__[cla][nod][cla]0231__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.09440715883668904
filename: [cla][pop_roc]0203__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.09455630126771067
filename: [cla][pop_roc]0303__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0947054436987323
filename: [cla][jaz_blu]0170__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.09485458612975392
filename: [cla][jaz_blu]0210__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.09500372856077555
filename: [cla][jaz_blu]0273__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.09515287099179717
filename: 181__[cla][nod][cla]0215__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0953020134228188
filename: 156__[cla][no

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.10738255033557047
filename: [cla][pop_roc]0308__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1075316927665921
filename: [cla][pop_roc]0208__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.10768083519761372
filename: [cla][jaz_blu]0321__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.10782997762863535
filename: [cla][jaz_blu]0274__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.10797912005965697
filename: [cla][pop_roc]0294__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1081282624906786
filename: 112__[cla][nod][cla]0243__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.10827740492170022
filename: 053__[cla][nod][cla]0219__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.10842654735272185
filename: 112__[cla][nod][cla]0243__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.10857568978374348
filename: [cla][jaz_blu]0274__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1087248322147651
filename: [cla][jaz_blu]0321__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.10887397464578673
filename: [cla][pop_

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.12095451155853841
filename: 114__[cla][nod][cla]0250__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.12110365398956004
filename: 017__[cla][nod][cla]0150__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.12125279642058165
filename: [cla][jaz_blu]0283__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.12140193885160327
filename: 099__[cla][nod][cla]0218__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1215510812826249
filename: 047__[cla][nod][cla]0247__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.12170022371364653
filename: [cla][jaz_blu]0192__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.12184936614466815
filename: [cla][jaz_blu]0325__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.12199850857568978
filename: [cla][pop_roc]0290__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1221476510067114
filename: [cla][cla]0163__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.12229679343773303
filename: [cla][pop_roc]0193__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.12244593586875466
filename: [cla][c

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1343773303504847
filename: 127__[voi][dru][pop_roc]2477__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.13452647278150634
filename: 214__[voi][nod][cou_fol]2372__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.13467561521252797
filename: [voi][jaz_blu]2486__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1348247576435496
filename: [voi][pop_roc]2499__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.13497390007457122
filename: 079__[voi][dru][lat_sou]2289__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.13512304250559284
filename: 264__[voi][nod][cou_fol]2435__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.13527218493661447
filename: [voi][pop_roc]2337__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1354213273676361
filename: [voi][pop_roc]2354__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.13557046979865772
filename: [voi][pop_roc]2505__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.13571961222967935
filename: 112__[voi][dru][cou_fol]2427__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.135868

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.14720357941834453
filename: 020__[voi][nod][cou_fol]2404__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.14735272184936615
filename: [voi][pop_roc]2335__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.14750186428038778
filename: [voi][pop_roc]2360__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1476510067114094
filename: 251__[voi][dru][pop_roc]2308__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.14780014914243103
filename: [voi][pop_roc]2531__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.14794929157345266
filename: [voi][jaz_blu]2488__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.14809843400447428
filename: [voi][pop_roc]2540__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1482475764354959
filename: [voi][pop_roc]2344__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.14839671886651754
filename: [voi][pop_roc]2497__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.14854586129753916
filename: 023__[voi][dru][cou_fol]2420__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1486950037285608
filename

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1600298284862043
filename: [voi][jaz_blu]2488__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.16017897091722594
filename: [voi][pop_roc]2360__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.16032811334824756
filename: [voi][pop_roc]2531__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1604772557792692
filename: 251__[voi][dru][pop_roc]2308__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.16062639821029082
filename: 020__[voi][nod][cou_fol]2404__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.16077554064131244
filename: 244__[voi][nod][cou_fol]2441__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.16092468307233407
filename: [voi][jaz_blu]2484__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1610738255033557
filename: 171__[voi][dru][pop_roc]2315__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.16122296793437732
filename: 248__[voi][nod][cou_fol]2385__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.16137211036539895
filename: 207__[voi][dru][cou_fol]2414__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1727069351230425
filename: 258__[voi][dru][lat_sou]2452__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.17285607755406412
filename: [voi][pop_roc]2527__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.17300521998508575
filename: 010__[voi][dru][cou_fol]2367__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.17315436241610738
filename: 203__[voi][nod][cou_fol]2374__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.173303504847129
filename: 094__[voi][dru][pop_roc]2479__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.17345264727815063
filename: 224__[voi][nod][lat_sou]2284__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.17360178970917226
filename: 046__[voi][dru][lat_sou]2455__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.17375093214019388
filename: [voi][pop_roc]2544__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1739000745712155
filename: 235__[voi][dru][pop_roc]2328__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.17404921700223713
filename: 206__[voi][dru][pop_roc]2475__2.wav
[0. 0. 1. 0. 0

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.18538404175988069
filename: 033__[voi][nod][pop_roc]2467__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1855331841909023
filename: 087__[voi][dru][pop_roc]2462__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.18568232662192394
filename: 039__[voi][nod][cou_fol]2371__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.18583146905294556
filename: 194__[voi][nod][cou_fol]2370__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1859806114839672
filename: 099__[voi][nod][cou_fol]2399__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.18612975391498882
filename: [voi][pop_roc]2525__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.18627889634601044
filename: 072__[voi][dru][cou_fol]2406__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.18642803877703207
filename: [voi][pop_roc]2350__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1865771812080537
filename: [voi][pop_roc]2501__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.18672632363907532
filename: [voi][pop_roc]2529__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.19791200596569725
filename: 166__[voi][nod][pop_roc]2312__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.19806114839671887
filename: [voi][pop_roc]2516__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.1982102908277405
filename: 114__[voi][dru][lat_sou]2454__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.19835943325876212
filename: 067__[voi][dru][pop_roc]2309__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.19850857568978375
filename: 241__[voi][nod][cou_fol]2421__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.19865771812080538
filename: 125__[voi][dru][cou_fol]2405__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.198806860551827
filename: 241__[voi][nod][cou_fol]2421__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.19895600298284863
filename: 067__[voi][dru][pop_roc]2309__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.19910514541387025
filename: 166__[voi][nod][pop_roc]2312__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.19925428784489188
filename: [voi][pop_roc]2494__1.wav
[0. 0. 1. 0. 

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.21058911260253543
filename: 175__[voi][dru][pop_roc]2327__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.21073825503355706
filename: 093__[voi][nod][cou_fol]2383__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.21088739746457869
filename: 037__[voi][dru][pop_roc]2473__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2110365398956003
filename: [voi][pop_roc]2359__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.21118568232662194
filename: [voi][pop_roc]2508__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.21133482475764356
filename: 216__[voi][dru][pop_roc]2298__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.21148396718866516
filename: 227__[voi][nod][pop_roc]2311__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2116331096196868
filename: 222__[voi][dru][pop_roc]2481__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2117822520507084
filename: [voi][pop_roc]2504__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.21193139448173004
filename: [voi][pop_roc]2355__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2232662192393736
filename: [voi][pop_roc]2518__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.22341536167039522
filename: [voi][pop_roc]2349__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.22356450410141684
filename: [voi][pop_roc]2361__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.22371364653243847
filename: [voi][pop_roc]2530__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2238627889634601
filename: [voi][pop_roc]2530__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.22401193139448172
filename: [voi][pop_roc]2361__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.22416107382550335
filename: [voi][pop_roc]2349__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.22431021625652497
filename: [voi][pop_roc]2518__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2244593586875466
filename: 052__[voi][nod][cou_fol]2396__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.22460850111856823
filename: [voi][jaz_blu]2356__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.22475764354958985
filename: 213__[voi][nod][co

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.23594332587621178
filename: [voi][pop_roc]2341__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2360924683072334
filename: 004__[voi][nod][pop_roc]2332__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.23624161073825503
filename: [voi][pop_roc]2538__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.23639075316927666
filename: 196__[voi][nod][cou_fol]2417__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.23653989560029828
filename: [voi][pop_roc]2534__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2366890380313199
filename: 243__[voi][dru][pop_roc]2325__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.23683818046234154
filename: [voi][pop_roc]2353__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.23698732289336316
filename: 138__[voi][dru][pop_roc]2297__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2371364653243848
filename: [voi][pop_roc]2502__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2372856077554064
filename: 059__[voi][nod][cou_fol]2447__2.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2374347

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.2487695749440716
filename: 002__[voi][dru][cou_fol]2411__3.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.24891871737509322
filename: [voi][pop_roc]2528__1.wav
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
0.24906785980611484
filename: [gac][pop_roc]0599__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.24921700223713647
filename: [gac][pop_roc]0684__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2493661446681581
filename: [gac][pop_roc]0730__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.24951528709917972
filename: 202__[gac][dru][cou_fol]0673__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.24966442953020135
filename: [gac][pop_roc]0630__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.24981357196122297
filename: [gac][pop_roc]0550__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2499627143922446
filename: [gac][jaz_blu]0598__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2501118568232662
filename: [gac][jaz_blu]0532__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.25026099925428785
filename: [gac][pop

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.26249067859806113
filename: [gac][pop_roc]0732__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2626398210290828
filename: 195__[gac][nod][cou_fol]0773__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2627889634601044
filename: [gac][cla]0585__2.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.26293810589112604
filename: [gac][cla]0632__2.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.26308724832214764
filename: [gac][cla]0667__3.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2632363907531693
filename: [gac][pop_roc]0679__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2633855331841909
filename: [gac][pop_roc]0564__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.26353467561521254
filename: 122__[gac][nod][cou_fol]0715__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.26368381804623414
filename: [gac][pop_roc]0704__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2638329604772558
filename: [gac][pop_roc]0604__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2639821029082774
filename: [gac][pop_roc]0604__2.w

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2759134973900075
filename: [gac][pop_roc]0655__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2760626398210291
filename: 051__[gac][dru][pop_roc]0624__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.27621178225205073
filename: [gac][jaz_blu]0549__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.27636092468307233
filename: [gac][pop_roc]0556__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.276510067114094
filename: [gac][cla]0548__1.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2766592095451156
filename: 133__[gac][dru][jaz_blu]0808__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.27680835197613723
filename: [gac][cla]0600__2.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.27695749440715883
filename: [gac][cla]0600__3.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2771066368381805
filename: 133__[gac][dru][jaz_blu]0808__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2772557792692021
filename: 051__[gac][dru][pop_roc]0624__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.27740492170022374
filename: [gac

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.28933631618195377
filename: [gac][pop_roc]0570__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.28948545861297537
filename: [gac][cla]0591__1.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.289634601043997
filename: [gac][jaz_blu]0524__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2897837434750186
filename: [gac][jaz_blu]0559__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.28993288590604027
filename: [gac][pop_roc]0726__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.29008202833706187
filename: [gac][pop_roc]0546__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2902311707680835
filename: [gac][jaz_blu]0639__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2903803131991051
filename: [gac][pop_roc]0537__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2905294556301268
filename: 170__[gac][nod][pop_roc]0628__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.2906785980611484
filename: [gac][cla]0529__3.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.29082774049217003
filename: [gac][pop_roc]0680__3.wav
[0. 

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.30320656226696496
filename: [gac][jaz_blu]0641__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.30335570469798656
filename: [gac][pop_roc]0723__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3035048471290082
filename: [gac][pop_roc]0594__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3036539895600298
filename: [gac][pop_roc]0697__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.30380313199105147
filename: [gac][pop_roc]0520__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.30395227442207307
filename: [gac][cla]0615__1.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3041014168530947
filename: [gac][pop_roc]0689__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3042505592841163
filename: 052__[gac][nod][cou_fol]0769__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.30439970171513797
filename: [gac][jaz_blu]0574__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.30454884414615957
filename: [gac][cla]0575__3.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3046979865771812
filename: [gac][cla]0664__1.wav
[0. 1.

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3169276659209545
filename: [gac][cla]0530__1.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.31707680835197616
filename: [gac][cla]0553__1.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.31722595078299776
filename: [gac][cla]0666__2.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3173750932140194
filename: [gac][pop_roc]0678__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.317524235645041
filename: [gac][cla]0633__3.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.31767337807606266
filename: [gac][pop_roc]0687__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.31782252050708426
filename: [gac][pop_roc]0705__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3179716629381059
filename: [gac][pop_roc]0605__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3181208053691275
filename: [gac][pop_roc]0650__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.31826994780014917
filename: [gac][pop_roc]0721__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.31841909023117076
filename: [gac][cla]0588__3.wav
[0. 1. 0. 1. 0. 0. 0. 0. 

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3303504847129008
filename: [gac][pop_roc]0701__3.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.33049962714392245
filename: [gac][pop_roc]0580__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.33064876957494405
filename: [gac][pop_roc]0737__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3307979120059657
filename: [gac][cla]0561__1.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3309470544369873
filename: 082__[gac][nod][cou_fol]0670__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.33109619686800895
filename: [gac][jaz_blu]0593__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.33124533929903055
filename: 054__[gac][dru][cou_fol]0763__1.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3313944817300522
filename: [gac][pop_roc]0646__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3315436241610738
filename: [gac][cla]0658__2.wav
[0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.33169276659209546
filename: [gac][pop_roc]0625__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.33184190902311705
filename: [gac][pop_roc]0725

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.34392244593586874
filename: [gac][pop_roc]0547__2.wav
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
0.3440715883668904
filename: 137__[gel][dru][pop_roc]0940__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.344220730797912
filename: 244__[gel][dru][jaz_blu]0787__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.34436987322893364
filename: 243__[gel][dru][jaz_blu]0796__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.34451901565995524
filename: 220__[gel][---][pop_roc]0942__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3446681580909769
filename: 066__[gel][dru][jaz_blu]0820__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3448173005219985
filename: [gel][pop_roc]1026__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.34496644295302015
filename: 080__[gel][dru][jaz_blu]0809__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.34511558538404175
filename: 242__[gel][dru][jaz_blu]0818__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3452647278150634
filename: [gel][pop_roc]0919__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3567486950037286
filename: 246__[gel][dru][pop_roc]0936__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3568978374347502
filename: 031__[gel][dru][pop_roc]0974__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.35704697986577183
filename: 175__[gel][dru][jaz_blu]0805__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.35719612229679343
filename: [gel][pop_roc]0868__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3573452647278151
filename: 060__[gel][dru][jaz_blu]0824__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3574944071588367
filename: [gel][pop_roc]0919__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.35764354958985833
filename: [gel][jaz_blu]1011__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.35779269202087993
filename: 242__[gel][dru][jaz_blu]0818__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3579418344519016
filename: [gel][pop_roc]1026__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3580909768829232
filename: 139__[gel][dru][cou_fol]0764__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.36972408650261
filename: [gel][pop_roc]0738__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3698732289336316
filename: [gel][pop_roc]0878__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.37002237136465327
filename: 072__[gel][dru][pop_roc]0956__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.37017151379567487
filename: [gel][pop_roc]0887__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3703206562266965
filename: [gel][pop_roc]0987__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3704697986577181
filename: [gel][jaz_blu]0998__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3706189410887398
filename: [gel][pop_roc]0738__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.37076808351976137
filename: [gel][pop_roc]0878__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.370917225950783
filename: 072__[gel][dru][pop_roc]0956__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3710663683818046
filename: 090__[gel][dru][jaz_blu]0781__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3712155108128262
filename: 151__[

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3825503355704698
filename: 052__[gel][dru][pop_roc]0963__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3826994780014914
filename: 079__[gel][dru][pop_roc]0958__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.38284862043251305
filename: [gel][pop_roc]0891__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.38299776286353465
filename: 168__[gel][dru][jaz_blu]0826__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3831469052945563
filename: 142__[gel][dru][cou_fol]0760__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3832960477255779
filename: 168__[gel][dru][jaz_blu]0826__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.38344519015659956
filename: 025__[gel][dru][jaz_blu]0806__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.38359433258762116
filename: 140__[gel][dru][jaz_blu]0819__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3837434750186428
filename: [gel][pop_roc]0913__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3838926174496644
filename: [gel][pop_roc]0891__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3953765846383296
filename: [gel][pop_roc]0743__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.39552572706935124
filename: [gel][pop_roc]0903__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.39567486950037284
filename: 218__[gel][dru][pop_roc]0862__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3958240119313945
filename: 250__[gel][dru][pop_roc]0960__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3959731543624161
filename: 214__[gel][dru][jaz_blu]0780__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.39612229679343774
filename: 245__[gel][nod][jaz_blu]0821__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.39627143922445934
filename: [gel][pop_roc]1022__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.396420581655481
filename: 154__[gel][dru][pop_roc]0836__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.3965697240865026
filename: 154__[gel][dru][pop_roc]0836__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.39671886651752425
filename: 232__[gel][dru][cou_fol]0758__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4082028337061894
filename: [gel][pop_roc]0922__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.408351976137211
filename: 178__[gel][dru][cou_fol]0746__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4085011185682327
filename: [gel][pop_roc]0896__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4086502609992543
filename: 007__[gel][dru][pop_roc]0943__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.40879940343027593
filename: 177__[gel][nod][jaz_blu]0803__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.40894854586129753
filename: 177__[gel][nod][jaz_blu]0803__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4090976882923192
filename: 131__[gel][dru][pop_roc]0945__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4092468307233408
filename: 007__[gel][dru][pop_roc]0943__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.40939597315436244
filename: [gel][pop_roc]0914__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.40954511558538403
filename: [gel][pop_roc]0896__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4210290827740492
filename: 165__[gel][dru][cou_fol]0745__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.42117822520507087
filename: 102__[gel][dru][jaz_blu]0813__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.42132736763609246
filename: [gel][pop_roc]0904__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4214765100671141
filename: 240__[gel][dru][jaz_blu]0791__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4216256524981357
filename: 160__[gel][dru][pop_roc]0832__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.42177479492915737
filename: [gel][pop_roc]0739__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.42192393736017897
filename: [gel][pop_roc]0879__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4220730797912006
filename: 069__[gel][dru][cou_fol]0762__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4222222222222222
filename: 219__[gel][dru][pop_roc]0983__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4223713646532439
filename: [gel][jaz_blu]0905__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.43400447427293065
filename: 253__[gel][dru][pop_roc]0979__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.43415361670395225
filename: [gel][pop_roc]0740__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4343027591349739
filename: [gel][pop_roc]0900__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4344519015659955
filename: [gel][pop_roc]0882__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.43460104399701716
filename: [gel][jaz_blu]1008__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.43475018642803875
filename: 056__[gel][nod][jaz_blu]0794__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4348993288590604
filename: [gel][pop_roc]1017__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.435048471290082
filename: 036__[gel][dru][jaz_blu]0785__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.43519761372110366
filename: 241__[gel][dru][pop_roc]0967__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.43534675615212526
filename: 235__[gel][nod][jaz_blu]0802__1.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.43549589

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.44683072334079044
filename: 082__[gel][dru][jaz_blu]0779__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4469798657718121
filename: [gel][jaz_blu]1014__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4471290082028337
filename: 103__[gel][dru][cou_fol]0676__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.44727815063385534
filename: 184__[gel][dru][pop_roc]0863__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.44742729306487694
filename: 044__[gel][dru][pop_roc]0951__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4475764354958986
filename: [gel][pop_roc]1023__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4477255779269202
filename: 023__[gel][dru][pop_roc]0855__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.44787472035794185
filename: 171__[gel][dru][jaz_blu]0815__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.44802386278896345
filename: [gel][pop_roc]0892__2.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
0.4481730052199851
filename: [gel][jaz_blu]1030__3.wav
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.45995525727069353
filename: [org][pop_roc]1130__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4601043997017151
filename: [org][jaz_blu]1107__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4602535421327368
filename: [org][jaz_blu]1232__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4604026845637584
filename: [org][jaz_blu]1185__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.46055182699478003
filename: [org][jaz_blu]1251__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.46070096942580163
filename: [org][jaz_blu]1164__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4608501118568233
filename: 110__[org][dru][jaz_blu]1117__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4609992542878449
filename: [org][pop_roc]1053__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.46114839671886654
filename: 001__[org][dru][jaz_blu]1123__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.46129753914988814
filename: [org][pop_roc]1242__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4614466815809098
filename: [org][pop_r

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4733780760626398
filename: [org][pop_roc]1075__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4735272184936615
filename: [org][pop_roc]1240__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.47367636092468307
filename: [org][jaz_blu]1195__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4738255033557047
filename: [org][jaz_blu]1277__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4739746457867263
filename: [org][jaz_blu]1206__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.474123788217748
filename: [org][pop_roc]1079__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4742729306487696
filename: [org][jaz_blu]1066__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4744220730797912
filename: [org][pop_roc]1219__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4745712155108128
filename: [org][jaz_blu]1166__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4747203579418344
filename: [org][jaz_blu]1253__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4748695003728561
filename: [org][jaz_blu]1199__2.wav
[0. 0. 0. 

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.48709917971662936
filename: [org][pop_roc]1128__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.487248322147651
filename: [org][pop_roc]1248__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4873974645786726
filename: [org][jaz_blu]1202__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.48754660700969427
filename: [org][pop_roc]1260__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.48769574944071586
filename: [org][pop_roc]1055__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4878448918717375
filename: [org][pop_roc]1235__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4879940343027591
filename: [org][pop_roc]1235__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.48814317673378077
filename: [org][pop_roc]1055__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.48829231916480237
filename: [org][pop_roc]1248__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.488441461595824
filename: [org][pop_roc]1128__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.4885906040268456
filename: 132__[org][dru][jaz_blu]1119__2.w

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5008202833706189
filename: [org][jaz_blu]1044__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5009694258016406
filename: [org][jaz_blu]1271__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5011185682326622
filename: [org][jaz_blu]1271__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5012677106636838
filename: [org][jaz_blu]1111__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5014168530947054
filename: [org][jaz_blu]1193__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5015659955257271
filename: [org][pop_roc]1225__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5017151379567487
filename: [org][jaz_blu]1172__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5018642803877703
filename: [org][jaz_blu]1072__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5020134228187919
filename: [org][jaz_blu]1212__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5021625652498136
filename: [org][pop_roc]1258__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5023117076808352
filename: [org][pop_roc]1229__2.wav
[0. 0. 0. 

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5146905294556301
filename: [org][pop_roc]1064__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5148396718866518
filename: [org][pop_roc]1131__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5149888143176734
filename: [org][pop_roc]1140__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.515137956748695
filename: [org][jaz_blu]1188__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5152870991797166
filename: [org][pop_roc]1220__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5154362416107383
filename: [org][pop_roc]1115__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5155853840417599
filename: [org][jaz_blu]1177__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5157345264727815
filename: [org][pop_roc]1068__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5158836689038031
filename: [org][jaz_blu]1041__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5160328113348247
filename: [org][jaz_blu]1096__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5161819537658464
filename: [org][jaz_blu]1114__2.wav
[0. 0. 0. 0

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5285607755406413
filename: [org][jaz_blu]1198__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5287099179716629
filename: [org][jaz_blu]1207__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5288590604026846
filename: [org][pop_roc]1218__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5290082028337062
filename: [org][jaz_blu]1167__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5291573452647278
filename: [org][jaz_blu]1067__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5293064876957494
filename: [org][pop_roc]1218__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5294556301267711
filename: [org][jaz_blu]1207__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5296047725577927
filename: [org][jaz_blu]1198__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5297539149888143
filename: [org][pop_roc]1050__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5299030574198359
filename: [org][pop_roc]1150__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5300521998508576
filename: [org][pop_roc]1230__3.wav
[0. 0. 0. 

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5421327367636093
filename: [org][pop_roc]1257__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5422818791946309
filename: [org][jaz_blu]1082__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5424310216256525
filename: [org][jaz_blu]1100__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5425801640566741
filename: [org][jaz_blu]1182__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5427293064876958
filename: [org][jaz_blu]1203__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5428784489187174
filename: [org][jaz_blu]1163__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.543027591349739
filename: [org][pop_roc]1234__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5431767337807606
filename: [org][pop_roc]1083__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5433258762117823
filename: 079__[org][dru][jaz_blu]1122__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5434750186428039
filename: [org][pop_roc]1245__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5436241610738255
filename: [org][jaz_blu]1190__2.wav
[

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5557046979865772
filename: [org][jaz_blu]1073__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5558538404175988
filename: [org][pop_roc]1259__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5560029828486205
filename: [org][pop_roc]1144__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5561521252796421
filename: [org][pop_roc]1224__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5563012677106637
filename: [org][pop_roc]1093__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5564504101416853
filename: [org][pop_roc]1247__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.556599552572707
filename: [org][pop_roc]1127__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5567486950037286
filename: [org][jaz_blu]1045__3.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5568978374347502
filename: [org][jaz_blu]1092__1.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5570469798657718
filename: [org][jaz_blu]1110__2.wav
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.5571961222967934
filename: [org][jaz_blu]1192__1.wav
[0. 0. 0. 0

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5694258016405668
filename: [pia][jaz_blu]1298__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5695749440715884
filename: [pia][cla]1362__1.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.56972408650261
filename: [pia][pop_roc]1287__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5698732289336316
filename: [pia][cla]1337__1.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5700223713646533
filename: 261__[pia][dru][jaz_blu]1427__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5701715137956749
filename: [pia][jaz_blu]1463__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5703206562266965
filename: [pia][cla]1499__2.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5704697986577181
filename: 204__[pia][nod][cla]1401__3.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5706189410887398
filename: [pia][jaz_blu]1482__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5707680835197614
filename: [pia][jaz_blu]1500__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.570917225950783
filename: 222__[pia][nod][pop_roc]1438__1.wav

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5828486204325131
filename: [pia][pop_roc]1289__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5829977628635347
filename: [pia][pop_roc]1289__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5831469052945563
filename: [pia][jaz_blu]1492__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.583296047725578
filename: [pia][jaz_blu]1510__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5834451901565996
filename: 051__[pia][dru][jaz_blu]1431__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5835943325876212
filename: [pia][cla]1497__1.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5837434750186428
filename: 228__[pia][nod][pop_roc]1437__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5838926174496645
filename: [pia][cla]1327__2.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5840417598806861
filename: [pia][jaz_blu]1473__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5841909023117077
filename: [pia][jaz_blu]1480__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5843400447427293
filename: [pia][jaz_blu]1502__1.wav

[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5965697240865027
filename: [pia][jaz_blu]1530__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5967188665175243
filename: [pia][cla]1448__2.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5968680089485459
filename: [pia][jaz_blu]1484__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5970171513795675
filename: [pia][cla]1307__2.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5971662938105892
filename: [pia][cla]1456__2.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5973154362416108
filename: [pia][cla]1352__3.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5974645786726324
filename: [pia][jaz_blu]1475__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.597613721103654
filename: 093__[pia][dru][jaz_blu]1428__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5977628635346757
filename: [pia][cla]1458__3.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5979120059656973
filename: [pia][jaz_blu]1359__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.5980611483967189
filename: 215__[pia][dru][jaz_blu]1432__3.wav
[0. 0. 0. 0

[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6101416853094705
filename: [pia][jaz_blu]1520__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6102908277404921
filename: 056__[pia][nod][cla]1385__2.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6104399701715137
filename: 196__[pia][nod][pop_roc]1439__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6105891126025355
filename: [pia][cla]1458__1.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.610738255033557
filename: [pia][jaz_blu]1371__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6108873974645787
filename: [pia][jaz_blu]1475__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6110365398956003
filename: 093__[pia][dru][jaz_blu]1428__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.611185682326622
filename: [pia][pop_roc]1332__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6113348247576436
filename: [pia][jaz_blu]1529__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6114839671886652
filename: 160__[pia][nod][jaz_blu]1433__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6116331096196868
filename: [pia][

[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6235645041014168
filename: 144__[pia][nod][cla]1380__2.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6237136465324384
filename: [pia][cla]1312__2.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6238627889634601
filename: 124__[pia][nod][jaz_blu]1426__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6240119313944817
filename: [pia][pop_roc]1286__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6241610738255033
filename: 152__[pia][dru][pop_roc]1440__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6243102162565249
filename: [pia][jaz_blu]1366__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6244593586875467
filename: 254__[pia][nod][cla]1406__1.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6246085011185682
filename: [pia][jaz_blu]1483__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6247576435495898
filename: [pia][pop_roc]1536__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6249067859806114
filename: 160__[pia][nod][jaz_blu]1433__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6250559284116332
filename

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6369873228933631
filename: 157__[pia][nod][cla]1400__2.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6371364653243848
filename: [pia][cla]1341__3.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6372856077554064
filename: 086__[pia][dru][jaz_blu]1424__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.637434750186428
filename: 118__[pia][dru][jaz_blu]1429__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6375838926174496
filename: [pia][cla]1369__2.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6377330350484713
filename: 239__[pia][nod][cla]1391__3.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6378821774794929
filename: 072__[pia][nod][cla]1395__1.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6380313199105145
filename: [pia][jaz_blu]1523__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6381804623415361
filename: [pia][jaz_blu]1372__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6383296047725578
filename: [pia][cla]1322__3.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6384787472035794
filename: [pia][pop_r

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6504101416853094
filename: [pia][pop_roc]1302__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6505592841163311
filename: [pia][jaz_blu]1360__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6507084265473527
filename: [pia][jaz_blu]1531__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6508575689783743
filename: [pia][jaz_blu]1485__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6510067114093959
filename: [pia][jaz_blu]1507__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6511558538404176
filename: [pia][jaz_blu]1356__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6513049962714392
filename: [pia][pop_roc]1349__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6514541387024608
filename: [pia][jaz_blu]1452__3.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6516032811334824
filename: [pia][pop_roc]1334__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6517524235645041
filename: [pia][cla]1284__3.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6519015659955257
filename: 229__[pia][nod][jaz_blu]1434__3.wav
[0. 

[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.664131245339299
filename: 101__[pia][nod][cla]1399__2.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6642803877703206
filename: [pia][jaz_blu]1509__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6644295302013423
filename: 190__[pia][dru][jaz_blu]1435__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6645786726323639
filename: [pia][jaz_blu]1358__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6647278150633855
filename: [pia][cla]1375__3.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6648769574944071
filename: [pia][jaz_blu]1474__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6650260999254288
filename: [pia][cla]1308__3.wav
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6651752423564504
filename: 224__[pia][dru][cou_fol]1422__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.665324384787472
filename: [pia][jaz_blu]1354__1.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6654735272184936
filename: [pia][jaz_blu]1487__2.wav
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
0.6656226696495153
filename: [pia][jaz_blu]1505__

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6775540641312453
filename: 136__[sax][dru][pop_roc]1721__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.677703206562267
filename: 085__[sax][nod][cla]1693__2.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6778523489932886
filename: 063__[sax][nod][cla]1677__2.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6780014914243102
filename: [sax][cla]1657__3.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6781506338553318
filename: 222__[sax][dru][jaz_blu]1720__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6782997762863535
filename: [sax][jaz_blu]1634__3.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6784489187173751
filename: [sax][cla]1602__2.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6785980611483967
filename: [sax][jaz_blu]1734__3.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6787472035794183
filename: [sax][jaz_blu]1649__3.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.67889634601044
filename: [sax][pop_roc]1603__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6790454884414616
filename: [sax][jaz_blu]1

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.69082774049217
filename: [sax][pop_roc]1563__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6909768829231916
filename: [sax][jaz_blu]1634__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6911260253542133
filename: [sax][jaz_blu]1734__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6912751677852349
filename: [sax][cla]1657__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6914243102162565
filename: [sax][jaz_blu]1780__3.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6915734526472781
filename: 010__[sax][nod][cla]1692__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6917225950782998
filename: 098__[sax][nod][cla]1685__2.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6918717375093214
filename: 181__[sax][nod][cla]1660__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.692020879940343
filename: [sax][jaz_blu]1757__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6921700223713646
filename: [sax][cla]1749__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.6923191648023863
filename: 065__[sax][nod][cla]1672__3.w

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7045488441461596
filename: [sax][jaz_blu]1568__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7046979865771812
filename: [sax][cla]1698__3.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7048471290082028
filename: [sax][jaz_blu]1651__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7049962714392245
filename: [sax][jaz_blu]1564__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7051454138702461
filename: [sax][cla]1732__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7052945563012677
filename: 080__[sax][dru][jaz_blu]1714__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7054436987322893
filename: [sax][cla]1751__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.705592841163311
filename: 006__[sax][nod][cla]1686__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7057419835943326
filename: [sax][jaz_blu]1767__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7058911260253542
filename: [sax][jaz_blu]1564__3.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7060402684563758
filename: [sax][cla]1698__2.wav
[0. 1. 0. 0

[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7182699478001492
filename: [sax][jaz_blu]1737__3.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7184190902311708
filename: [sax][jaz_blu]1580__3.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7185682326621924
filename: [sax][cla]1601__2.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.718717375093214
filename: [sax][pop_roc]1628__3.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7188665175242357
filename: [sax][jaz_blu]1762__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7190156599552573
filename: [sax][cla]1754__3.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7191648023862789
filename: [sax][pop_roc]1628__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7193139448173005
filename: [sax][cla]1754__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7194630872483222
filename: [sax][jaz_blu]1580__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7196122296793438
filename: [sax][jaz_blu]1737__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7197613721103654
filename: 223__[sax][nod][cla]1674__1.wav
[0. 1. 0. 0. 0. 0

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7318419090231171
filename: [sax][jaz_blu]1656__3.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7319910514541387
filename: [sax][jaz_blu]1781__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7321401938851603
filename: [sax][cla]1635__3.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.732289336316182
filename: 024__[sax][nod][cla]1689__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7324384787472036
filename: [sax][cla]1648__3.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7325876211782252
filename: [sax][cla]1748__3.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7327367636092468
filename: 058__[sax][nod][cla]1662__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7328859060402685
filename: [sax][cla]1639__3.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7330350484712901
filename: [sax][pop_roc]1610__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7331841909023117
filename: [sax][jaz_blu]1772__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7333333333333333
filename: [sax][cla]1644__3.wav
[0. 1. 0. 0. 0. 0. 

[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.745413870246085
filename: [sax][cla]1723__2.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7455630126771067
filename: [sax][jaz_blu]1740__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7457121551081283
filename: 067__[sax][nod][cla]1666__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7458612975391499
filename: 128__[sax][nod][jaz_blu]1712__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7460104399701715
filename: [sax][jaz_blu]1640__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7461595824011932
filename: [sax][pop_roc]1622__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7463087248322148
filename: [sax][pop_roc]1595__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7464578672632364
filename: [sax][jaz_blu]1768__3.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.746607009694258
filename: [sax][jaz_blu]1594__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7467561521252797
filename: 134__[sax][nod][cla]1663__1.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7469052945563013
filename: [sax][jaz_blu]1776__

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.758985831469053
filename: 012__[sax][nod][jaz_blu]1713__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7591349739000746
filename: [sax][jaz_blu]1633__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7592841163310962
filename: [sax][jaz_blu]1565__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7594332587621179
filename: 094__[sax][dru][jaz_blu]1703__2.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7595824011931395
filename: 036__[sax][nod][cla]1664__3.wav
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7597315436241611
filename: [sax][pop_roc]1585__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7598806860551827
filename: 170__[sax][dru][jaz_blu]1707__1.wav
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.7600298284862044
filename: [tru][cla]2014__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.760178970917226
filename: [tru][pop_roc]1968__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7603281133482476
filename: [tru][pop_roc]2035__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7604772557792692
filename: [tru][

[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7725577926920209
filename: [tru][jaz_blu]1967__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7727069351230426
filename: [tru][pop_roc]1999__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7728560775540642
filename: [tru][jaz_blu]1979__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7730052199850858
filename: [tru][cla]1912__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7731543624161074
filename: [tru][jaz_blu]2024__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.773303504847129
filename: [tru][jaz_blu]1979__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7734526472781507
filename: [tru][jaz_blu]2059__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7736017897091723
filename: [tru][pop_roc]2046__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7737509321401939
filename: [tru][cla]2051__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7739000745712155
filename: [tru][jaz_blu]1967__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7740492170022372
filename: [tru][jaz_blu]1932__2.wav
[0. 0. 0. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.786428038777032
filename: [tru][cla]1951__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7865771812080536
filename: [tru][pop_roc]1970__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7867263236390754
filename: [tru][cla]1904__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.786875466070097
filename: [tru][pop_roc]2078__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7870246085011185
filename: [tru][jaz_blu]2032__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7871737509321401
filename: [tru][pop_roc]2050__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7873228933631619
filename: [tru][pop_roc]1958__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7874720357941835
filename: [tru][cla]1879__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.787621178225205
filename: [tru][cla]1879__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7877703206562267
filename: [tru][pop_roc]1958__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.7879194630872484
filename: [tru][pop_roc]2050__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8001491424310216
filename: [tru][jaz_blu]1880__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8002982848620432
filename: [tru][pop_roc]2040__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8004474272930648
filename: 203__[tru][dru][pop_roc]1992__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8005965697240865
filename: [tru][cla]2061__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8007457121551081
filename: [tru][jaz_blu]1957__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8008948545861297
filename: [tru][jaz_blu]2022__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8010439970171513
filename: [tru][pop_roc]1993__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.801193139448173
filename: [tru][pop_roc]1944__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8013422818791947
filename: [tru][jaz_blu]1926__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8014914243102162
filename: [tru][cla]2010__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8016405667412378
filename: [tru][jaz_blu]1945__1.wav
[0. 0. 0.

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8140193885160328
filename: 014__[tru][dru][jaz_blu]2000__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8141685309470544
filename: [tru][cla]1911__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.814317673378076
filename: [tru][cla]1893__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8144668158090976
filename: [tru][cla]1872__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8146159582401193
filename: [tru][jaz_blu]1919__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8147651006711409
filename: [tru][cla]2007__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8149142431021625
filename: [tru][pop_roc]1920__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8150633855331841
filename: [tru][cla]1954__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8152125279642058
filename: [tru][cla]2009__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8153616703952274
filename: [tru][cla]1929__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.815510812826249
filename: [tru][jaz_blu]1942__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.

[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.827889634601044
filename: [tru][pop_roc]1955__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8280387770320656
filename: [tru][jaz_blu]2017__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8281879194630872
filename: [tru][pop_roc]1900__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8283370618941088
filename: [tru][jaz_blu]2021__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8284862043251305
filename: [tru][cla]2062__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8286353467561521
filename: [tru][pop_roc]2043__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8287844891871737
filename: [tru][pop_roc]2043__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8289336316181953
filename: [tru][cla]2062__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.829082774049217
filename: [tru][jaz_blu]2021__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8292319164802386
filename: [tru][pop_roc]1900__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8293810589112602
filename: [tru][pop_roc]1882__1.wav
[0. 0. 0. 0. 0. 0. 0

[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8416107382550335
filename: [tru][jaz_blu]2031__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8417598806860552
filename: [tru][pop_roc]2053__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8419090231170768
filename: [tru][jaz_blu]2019__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8420581655480984
filename: [tru][jaz_blu]1927__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.84220730797912
filename: [tru][cla]2011__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8423564504101417
filename: [tru][jaz_blu]1972__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8425055928411633
filename: [tru][pop_roc]1910__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8426547352721849
filename: [tru][jaz_blu]1972__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8428038777032065
filename: 108__[tru][dru][jaz_blu]1990__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8429530201342282
filename: [tru][cla]2011__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.8431021625652498
filename: [tru][jaz_blu]1927__3.wav
[0. 0. 0. 

[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8551826994780015
filename: [vio][pop_roc]2144__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8553318419090231
filename: [vio][pop_roc]2127__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8554809843400447
filename: [vio][cla]2087__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8556301267710664
filename: 108__[vio][nod][cou_fol]2193__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.855779269202088
filename: [vio][cla]2265__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8559284116331096
filename: 072__[vio][dru][cou_fol]2188__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8560775540641312
filename: 100__[vio][nod][cla]2183__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8562266964951528
filename: [vio][pop_roc]2101__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8563758389261745
filename: [vio][cla]2216__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8565249813571961
filename: [vio][jaz_blu]2281__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8566741237882177
filename: 105__[vio][nod][cla]217

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8686055182699478
filename: [vio][cla]2255__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8687546607009694
filename: [vio][jaz_blu]2108__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.868903803131991
filename: 114__[vio][nod][cla]2184__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8690529455630127
filename: [vio][cla]2103__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8692020879940343
filename: [vio][pop_roc]2121__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8693512304250559
filename: 174__[vio][nod][cla]2157__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8695003728560775
filename: [vio][cla]2263__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8696495152870992
filename: 137__[vio][nod][cou_fol]2190__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8697986577181208
filename: [vio][jaz_blu]2094__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8699478001491424
filename: [vio][jaz_blu]2116__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.870096942580164
filename: [vio][jaz_blu]2132__3.wav
[0

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8821774794929157
filename: [vio][pop_roc]2204__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8823266219239374
filename: 134__[vio][nod][cla]2156__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.882475764354959
filename: [vio][pop_roc]2251__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8826249067859806
filename: [vio][pop_roc]2251__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8827740492170022
filename: 134__[vio][nod][cla]2156__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8829231916480239
filename: 026__[vio][nod][cla]2148__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8830723340790455
filename: [vio][pop_roc]2204__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8832214765100671
filename: [vio][jaz_blu]2266__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8833706189410887
filename: [vio][jaz_blu]2233__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8835197613721104
filename: [vio][jaz_blu]2084__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.883668903803132
filename: [vio][jaz_blu]2106__

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8957494407158837
filename: [vio][jaz_blu]2093__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8958985831469053
filename: [vio][jaz_blu]2224__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8960477255779269
filename: [vio][cla]2219__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8961968680089486
filename: [vio][pop_roc]2126__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8963460104399702
filename: [vio][pop_roc]2246__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8964951528709918
filename: [vio][cla]2264__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8966442953020134
filename: [vio][pop_roc]2145__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8967934377330351
filename: [vio][pop_roc]2110__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8969425801640567
filename: [vio][pop_roc]2246__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8970917225950783
filename: [vio][jaz_blu]2093__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.8972408650260999
filename: [vio][jaz_blu]2224__2.wav
[0. 0. 0. 0. 0. 0.

[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9093214019388516
filename: [vio][jaz_blu]2125__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9094705443698732
filename: [vio][jaz_blu]2238__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9096196868008949
filename: 180__[vio][nod][cla]2211__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9097688292319165
filename: 009__[vio][nod][cla]2178__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9099179716629381
filename: [vio][jaz_blu]2117__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9100671140939597
filename: [vio][cla]2102__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9102162565249814
filename: [vio][cla]2283__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.910365398956003
filename: [vio][pop_roc]2276__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9105145413870246
filename: [vio][jaz_blu]2109__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9106636838180462
filename: 058__[vio][nod][cla]2174__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9108128262490679
filename: 083__[vio][dru][pop_roc]220

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9227442207307979
filename: [vio][pop_roc]2130__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9228933631618196
filename: [vio][cla]2112__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9230425055928412
filename: 143__[vio][nod][cla]2147__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9231916480238628
filename: [vio][cla]2256__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9233407904548844
filename: [vio][jaz_blu]2089__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9234899328859061
filename: [vio][pop_roc]2141__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9236390753169277
filename: 017__[vio][nod][cla]2153__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9237882177479493
filename: [vio][pop_roc]2096__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9239373601789709
filename: [vio][pop_roc]2088__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9240865026099926
filename: [vio][jaz_blu]2097__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
0.9242356450410142
filename: [vio][cla]2260__3.wav
[0. 1. 0. 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9361670395227443
filename: [flu][pop_roc]0476__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9363161819537659
filename: [flu][pop_roc]0476__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9364653243847875
filename: [flu][pop_roc]0372__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9366144668158091
filename: [flu][cla]0441__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9367636092468308
filename: 061__[flu][dru][pop_roc]0419__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9369127516778524
filename: [flu][cla]0373__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.937061894108874
filename: [flu][cla]0357__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9372110365398956
filename: [flu][pop_roc]0360__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9373601789709173
filename: [flu][jaz_blu]0453__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9375093214019389
filename: [flu][jaz_blu]0380__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9376584638329605
filename: [flu][cla]0349__3.wav
[0. 1. 0. 0. 0. 0

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9498881431767338
filename: [flu][jaz_blu]0500__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9500372856077554
filename: [flu][cla]0367__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9501864280387771
filename: [flu][pop_roc]0483__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9503355704697987
filename: [flu][pop_roc]0470__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9504847129008203
filename: [flu][jaz_blu]0447__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9506338553318419
filename: [flu][jaz_blu]0512__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9507829977628636
filename: [flu][jaz_blu]0459__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9509321401938852
filename: [flu][pop_roc]0491__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9510812826249068
filename: [flu][jaz_blu]0459__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9512304250559284
filename: 093__[flu][dru][pop_roc]0420__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9513795674869501
filename: [flu][pop_roc]0395__1.wav
[0. 

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.963758389261745
filename: [flu][cla]0402__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9639075316927666
filename: [flu][pop_roc]0364__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9640566741237883
filename: [flu][cla]0434__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9642058165548099
filename: [flu][jaz_blu]0461__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9643549589858315
filename: 058__[flu][nod][jaz_blu]0775__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.964504101416853
filename: [flu][jaz_blu]0445__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9646532438478748
filename: [flu][cla]0438__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9648023862788964
filename: [flu][cla]0369__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.964951528709918
filename: [flu][pop_roc]0472__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9651006711409396
filename: [flu][cla]0396__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9652498135719613
filename: [flu][cla]0426__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0.

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9776286353467561
filename: 155__[flu][nod][cou_fol]0416__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9777777777777777
filename: [flu][pop_roc]0479__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9779269202087995
filename: [flu][jaz_blu]0499__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.978076062639821
filename: [flu][cla]0362__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9782252050708427
filename: [flu][cla]0433__3.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9783743475018642
filename: [flu][pop_roc]0486__1.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.978523489932886
filename: [flu][pop_roc]0467__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9786726323639076
filename: [flu][jaz_blu]0450__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9788217747949292
filename: [flu][jaz_blu]0405__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9789709172259508
filename: [flu][jaz_blu]0405__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9791200596569725
filename: [flu][jaz_blu]0450__2.wav
[0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9913497390007457
filename: 009__[flu][nod][cou_fol]0410__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9914988814317673
filename: [flu][cla]0435__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9916480238627889
filename: [flu][jaz_blu]0448__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9917971662938105
filename: [flu][cla]0385__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9919463087248322
filename: [flu][pop_roc]0365__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9920954511558538
filename: [flu][jaz_blu]0456__2.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9922445935868754
filename: [flu][jaz_blu]0403__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.992393736017897
filename: [flu][jaz_blu]0503__3.wav
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9925428784489188
filename: [flu][cla]0389__1.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.9926920208799404
filename: [flu][cla]0427__2.wav
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
0.992841163310962
filename: [flu][cla]0376__2.wav
[0. 1. 0. 0. 0. 0. 0. 

In [3]:
audio_mfccs.shape
#6705 waveforms, 20 mfccs, 130 frames

x = []
for waveform in audio_mfccs:
    x.append(waveform.flatten())
    
x = np.array(x)

x.shape
    

(6705, 2600)

In [4]:
targets.shape


(6705, 11)

In [5]:
# create a dataset with 6705 samples
x_train, x_test, y_train, y_test = train_test_split(x, targets, test_size=.3)


# build model with 4 layers: 2600 --> 1305 --> 24 --> 11
model = tf.keras.models.Sequential([ #sequential=inputs move left to right
    tf.keras.layers.Dense(1305, input_dim=2600, activation="sigmoid"), #dense because all neurons are connected
    tf.keras.layers.Dense(24, activation="sigmoid"), #hidden  layer
    tf.keras.layers.Dense(11, activation="sigmoid") #output layer
])

# choose optimiser
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)#stochastic gradient descent

# compile model
model.compile(optimizer=optimizer, loss='mse')#mean squared error

# train model
model.fit(x_train, y_train, epochs=1000, shuffle=True)

# evaluate model on test set
print("\nEvaluation on the test set:")
model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/1000
147/147 [==============================] - 2s 7ms/step - loss: 0.1859
Epoch 2/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.1463
Epoch 3/1000
147/147 [==============================] - 1s 10ms/step - loss: 0.1303
Epoch 4/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.1206
Epoch 5/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.1141
Epoch 6/1000
147/147 [==============================] - 1s 10ms/step - loss: 0.1097
Epoch 7/1000
147/147 [==============================] - 2s 10ms/step - loss: 0.1065
Epoch 8/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.1041
Epoch 9/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.1023
Epoch 10/1000
147/147 [==============================] - 1s 10ms/step - loss: 0.1008
Epoch 11/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0996
Epoch 12/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.09

147/147 [==============================] - 1s 9ms/step - loss: 0.0850
Epoch 99/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0850
Epoch 100/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0849
Epoch 101/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0849
Epoch 102/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0848
Epoch 103/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0848
Epoch 104/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0847
Epoch 105/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0847
Epoch 106/1000
147/147 [==============================] - 1s 10ms/step - loss: 0.0846
Epoch 107/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0846
Epoch 108/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0845
Epoch 109/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.

147/147 [==============================] - 1s 8ms/step - loss: 0.0815
Epoch 195/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0815
Epoch 196/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0814
Epoch 197/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0814
Epoch 198/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0814
Epoch 199/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0814
Epoch 200/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0814
Epoch 201/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0813
Epoch 202/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0813
Epoch 203/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0813
Epoch 204/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0812
Epoch 205/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.

147/147 [==============================] - 1s 8ms/step - loss: 0.0793
Epoch 291/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0793
Epoch 292/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0792
Epoch 293/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0792A: 0s - loss:
Epoch 294/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0792A: 0s - 
Epoch 295/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0792
Epoch 296/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0792
Epoch 297/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0791
Epoch 298/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0791
Epoch 299/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0791
Epoch 300/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0791
Epoch 301/1000
147/147 [==============================] - 1

147/147 [==============================] - 1s 8ms/step - loss: 0.0772
Epoch 387/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0772
Epoch 388/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0772
Epoch 389/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0772
Epoch 390/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0772
Epoch 391/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0771
Epoch 392/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0771
Epoch 393/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0771
Epoch 394/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0771
Epoch 395/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0770
Epoch 396/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0770
Epoch 397/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.

147/147 [==============================] - 1s 8ms/step - loss: 0.0750
Epoch 483/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0750
Epoch 484/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0750
Epoch 485/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0750
Epoch 486/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0750
Epoch 487/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0749
Epoch 488/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0749
Epoch 489/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0749
Epoch 490/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0749
Epoch 491/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0748
Epoch 492/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0748
Epoch 493/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.

147/147 [==============================] - 1s 8ms/step - loss: 0.0728
Epoch 579/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0727
Epoch 580/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0727
Epoch 581/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0727
Epoch 582/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0726
Epoch 583/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0726
Epoch 584/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0726
Epoch 585/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0726
Epoch 586/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0725
Epoch 587/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0725
Epoch 588/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0725
Epoch 589/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.

147/147 [==============================] - 1s 9ms/step - loss: 0.0702
Epoch 675/1000
147/147 [==============================] - 1s 10ms/step - loss: 0.0701
Epoch 676/1000
147/147 [==============================] - 3s 19ms/step - loss: 0.0701
Epoch 677/1000
147/147 [==============================] - 2s 10ms/step - loss: 0.0701
Epoch 678/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0700
Epoch 679/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0700
Epoch 680/1000
147/147 [==============================] - 1s 10ms/step - loss: 0.0700
Epoch 681/1000
147/147 [==============================] - 2s 12ms/step - loss: 0.0699
Epoch 682/1000
147/147 [==============================] - 2s 13ms/step - loss: 0.0699
Epoch 683/1000
147/147 [==============================] - 2s 11ms/step - loss: 0.0699
Epoch 684/1000
147/147 [==============================] - 2s 12ms/step - loss: 0.0699
Epoch 685/1000
147/147 [==============================] - 2s 11ms/step -

147/147 [==============================] - 1s 10ms/step - loss: 0.0672
Epoch 771/1000
147/147 [==============================] - 2s 11ms/step - loss: 0.0672
Epoch 772/1000
147/147 [==============================] - 2s 15ms/step - loss: 0.0672
Epoch 773/1000
147/147 [==============================] - 2s 16ms/step - loss: 0.0671
Epoch 774/1000
147/147 [==============================] - 2s 15ms/step - loss: 0.0671
Epoch 775/1000
147/147 [==============================] - 2s 14ms/step - loss: 0.0671
Epoch 776/1000
147/147 [==============================] - 2s 14ms/step - loss: 0.0670
Epoch 777/1000
147/147 [==============================] - 2s 15ms/step - loss: 0.0670
Epoch 778/1000
147/147 [==============================] - 2s 11ms/step - loss: 0.0670
Epoch 779/1000
147/147 [==============================] - 2s 11ms/step - loss: 0.0669
Epoch 780/1000
147/147 [==============================] - 2s 12ms/step - loss: 0.0669
Epoch 781/1000
147/147 [==============================] - 1s 10ms/ste

Epoch 866/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0640
Epoch 867/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0640
Epoch 868/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0639
Epoch 869/1000
147/147 [==============================] - 1s 10ms/step - loss: 0.0639
Epoch 870/1000
147/147 [==============================] - 2s 15ms/step - loss: 0.0639
Epoch 871/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0638
Epoch 872/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0638
Epoch 873/1000
147/147 [==============================] - 2s 11ms/step - loss: 0.0638
Epoch 874/1000
147/147 [==============================] - 2s 11ms/step - loss: 0.0637
Epoch 875/1000
147/147 [==============================] - 3s 18ms/step - loss: 0.0637
Epoch 876/1000
147/147 [==============================] - 1s 10ms/step - loss: 0.0637
Epoch 877/1000
147/147 [==============================] - 1

Epoch 962/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0605
Epoch 963/1000
147/147 [==============================] - 1s 10ms/step - loss: 0.0605
Epoch 964/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0605
Epoch 965/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0604
Epoch 966/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0604
Epoch 967/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0604
Epoch 968/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0603
Epoch 969/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0603
Epoch 970/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0602
Epoch 971/1000
147/147 [==============================] - 1s 9ms/step - loss: 0.0602
Epoch 972/1000
147/147 [==============================] - 1s 8ms/step - loss: 0.0602
Epoch 973/1000
147/147 [==============================] - 1s 9ms

0.075740285217762

In [96]:
#evaluate

audio_file = 'IRMAS-TrainingData/gel/[gel]shesaid.wav'



signal, sr = librosa.load(audio_file)
signal_3s = signal[66150*4:66150*5]
mfcc = librosa.feature.mfcc(signal_3s, n_mfcc=20, sr=sr)

mfcc = np.array([mfcc.flatten()])
print(mfcc.shape)



pred = list(model.predict(mfcc)[0])

print(pred)
maxval = max(pred)

index = pred.index(maxval)

print(sub_folders[index])





/Users/abelardoriojas/opt/anaconda3/lib/python3.8/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


(1, 2600)
[0.059096783, 0.033693373, 0.14328215, 0.043064, 0.3810072, 0.11225462, 0.06413481, 0.08059853, 0.20839456, 0.067356795, 0.052128106]
gel


In [ ]:
mfcc.shape

In [95]:
ipd.Audio(signal_3s,rate=sr)

In [23]:
audio_file = 'IRMAS-TrainingData/gel/shesaid.wav'



signal, sr = librosa.load(audio_file)

/Users/abelardoriojas/opt/anaconda3/lib/python3.8/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


In [52]:
print(len(signal))

66150
